PrimerCore/Controllers/Coche1Controller.cs
using Microsoft.AspNetCore.Mvc;
using PrimerCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class Coche1Controller : Controller
    {
        private Coche car;

        public Coche1Controller(Coche car)
        {
            this.car = car;
        //    this.car.Marca = "VolksWagen";
        //    this.car.Modelo = "Escarabajo";
        //    this.car.Imagen = "VWEscarabajo.jpg";
        //    this.car.Velocidad = 0;
        //    this.car.VelocidadMaxima = 150;
        }
        public IActionResult Index()
        {
            return View(this.car);
        }
        [HttpPost]
        public IActionResult Index(string accion)
        {
            if(accion == "acelerar")
            {
                this.car.Acelerar();
            }
            else
            {
                this.car.Frenar();
            }
            return View(this.car);
        }
    }
}

PrimerCore/Controllers/Coche2Controller.cs
using Microsoft.AspNetCore.Mvc;
using PrimerCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class Coche2Controller : Controller
    {
        private Coche car;
        public Coche2Controller(Coche car)
        {
            this.car = car;
            //    this.car = new Coche();
            //    this.car.Marca = "VolksWagen";
            //    this.car.Modelo = "Escarabajo";
            //    this.car.Imagen = "VWEscarabajo.jpg";
            //    this.car.Velocidad = 0;
            //    this.car.VelocidadMaxima = 150;
        }
        public IActionResult Index()
        {
            return View(this.car);
        }
    }
}

PrimerCore/Controllers/PracticasController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class PracticasController : Controller
    {
        //esto es un get
        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult EjemploColecciones()
        {
            List<Comic> listacomics = new List<Comic>();
            Comic comic = new Comic();
            comic.Nombre = "Naruto";
            comic.Descripcion = "Ninjas";
            comic.Imagen = "https://www.formulatv.com/images/series/posters/100/135/dest_1.jpg";
            listacomics.Add(comic);
            Comic comic2 = new Comic();
            comic2.Nombre = "Batman";
            comic2.Descripcion = "Hombre murcielago";
            comic2.Imagen = "https://www.normaeditorial.com/upload/media/albumes/0001/07/thumb_6662_albumes_big.jpeg";
            listacomics.Add(comic2);
            return View(listacomics);
        }

        public IActionResult SumarNumerosGet()
        {
            ViewBag.Num1 = 2;
            ViewBag.Num2 = 7;
            ViewBag.Suma = ViewBag.Num1 + ViewBag.Num2;
            return View();
        }
        public IActionResult SumarNumerosPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SumarNumerosPost(int num1, int num2)
        {
            ViewBag.Num1 = num1;
            ViewBag.Num2 = num2;
            ViewBag.Suma = num1 + num2;
            return View();
        }

        public IActionResult TablaMultiplicar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult TablaMultiplicar(int num)
        {
            List<FilaTabla> listafilas = new List<FilaTabla>();
            for (int i = 1;i <= 10; i++)
            {
                FilaTabla fila = new FilaTabla();
                fila.Columna1 = num + " * " + i;
                fila.Columna2 = num * i;
                listafilas.Add(fila);
            }

            return View(listafilas);
        }
    }
}

PrimerCore/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PrimerCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimerCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger"
                               asp-controller="Informacion"
                               asp-action="Index">
                                Informacion
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:darkorchid"
                               asp-controller="Practicas"
                               asp-action="Menu">
                                Practicas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:darkgoldenrod"
                               asp-controller="Coche1"
                               asp-action="Index">
                                Coche 1
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:deeppink"
                               asp-controller="Coche2"
                               asp-action="Index">
                                Coche 2
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <a asp-controller="Prueba" asp-action="Index">
                Index de Prueba
            </a>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PrimerCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>