PrimerCore/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class InformacionController : Controller
    {
        //usamos la lista index como un menu
        public IActionResult Index()
        {
            //aqui enviamos la info, antes del return
            return View();
        }

        public IActionResult InformacionControllerView()
        {
            ViewBag.Nombre = "Alumno";
            ViewData["Descripcion"] = "Estoy aprendiendo Net Core";
            ViewBag.Year = 2021;
            return View();
        }
        public IActionResult InformacionControllerViewModel()
        {
            List<Persona> listapersonas = new List<Persona>();
            for (int i = 1; i <= 10; i++)
            {
                Persona per = new Persona();
                per.Nombre = "Persona " + i;
                per.Edad = 20 + i;
                per.Email = "persona" + i + "@correo.com";
                listapersonas.Add(per);
            }
            //enviamos el modelo a la vista
            return View(listapersonas);
        }

        public IActionResult InformacionGetViewController(String nombre, int edad)
        {
            ViewBag.Nombre = nombre;
            ViewBag.Edad = edad;
            return View();
        }
        [HttpGet]
        public IActionResult InformacionPostViewController()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InformacionPostViewController(Persona persona)
        {
            
            return View(persona);
        }
    }
}

PrimerCore/Views/Informacion/Index.cshtml
<h1>Menú información entre componentes MVC</h1>
@*Esto es un comentario en RAZOR*@
@* @{
    int numero = 14;
    String text = "Texto generado en Razor";
} 

<h3 style="color:red">@text</h3>

@if (numero > 0)
{
    numero = numero + 99;
    <p>Positivo, todo esto es en html</p>
}
else { 
<p>Negativo, todo html de nuevo</p>
}

@for (int i = 1; i <= 6; i++)
{
    int v = i * 2;
    <h2> @i x 2 = @v</h2>
}*@

<ul class="list-group">
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="InformacionControllerView">
            Enviar Info Controller -- View
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="InformacionControllerViewModel">
            Enviar Model Controller -- View
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="InformacionGetViewController"
           asp-route-nombre="Alumno Core GET"
           asp-route-edad="23">
            Get info de View -- Controller
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Informacion"
           asp-action="InformacionPostViewController">
            Post info de View -- Controller
        </a>
    </li>
</ul>

PrimerCore/Views/Informacion/InformacionControllerView.cshtml
<h1>Controller -- view</h1>

<a asp-controller="Informacion"
   asp-action="Index">
    Volver al menu
</a>

<hr/>

<h2 style="color:blue">
    Nombre: @ViewBag.Nombre
</h2>
<h2 style="color:brown">Descripción: @ViewBag.Descripcion</h2>
<h2 style="color:chartreuse">Año: @ViewBag.Year</h2>

PrimerCore/Views/Informacion/InformacionGetViewController.cshtml
<h1 style="color:deeppink">
    Información Get View Controller
</h1>
<a asp-controller="Informacion"
   asp-action="Index">
    Volver al menu
</a>
<hr/>



<h2>Datos recibidos: @ViewBag.Nombre, @ViewBag.Edad</h2>

PrimerCore/Views/Informacion/InformacionPostViewController.cshtml
@model Persona
<h1>Post View Controller</h1>

<a asp-controller="Informacion"
   asp-action="Index">
    Volver menu
</a>
<hr />

<form method="post">
    <label>Nombre: </label>
    <input type="text" name="nombre"
           class="form-control" /><br />
    <label>Edad: </label>
    <input type="number" name="edad"
           class="form-control" /><br />
    <label>Email: </label>
    <input type="email" name="email"
           class="form-control" /><br />
    <button class="btn btn-info">
        Enviar datos
    </button>
</form>
<hr />
@if (Model != null)
{
    <h3 style="color:darkviolet">
        @Model.Nombre @Model.Edad @Model.Email
    </h3>
}

PrimerCore/Views/Informacion/informacionControllerViewModel.cshtml
@model List<Persona>

<h1>Controller View Model</h1>

<a asp-controller="Informacion"
   asp-action="Index">
    Volver al menu
</a>
<hr/>

<table class="table table-dark">
    @foreach (Persona p in Model)
    {
        <tr>
            <td>@p.Nombre</td>
            <td>@p.Edad</td>
            <td>@p.Email</td>
        </tr>
    }
</table>