PrimerCore/Controllers/MatematicasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class MatematicasController : Controller
    {
        private List<int> GetNumerosRandom()
        {
            List<int> numeros = new List<int>();
            Random random = new Random();
            for (int i = 1; i <= 7; i++)
            {
                int num = random.Next(1, 100);
                numeros.Add(num);
            }
            return numeros;
        }

        private List<int> GetNumerosCollatz(int numero)
        {
            List<int> numeros = new List<int>();
            numeros.Add(numero);
            while (numero != 1)
            {
                if(numero%2 == 0)
                {
                    numero = numero / 2;
                }
                else
                {
                    numero = numero * 3 + 1;
                }
                numeros.Add(numero);
            }
            return numeros;
        }

        public IActionResult ConjeturaCollatz()
        {
            List<int> aleatorios = this.GetNumerosRandom();
            ViewBag.Random = aleatorios;
            return View();
        }
        [HttpPost]
        public IActionResult ConjeturaCollatz(int numero)
        {
            List<int> collatz = this.GetNumerosCollatz(numero);
            List<int> aleatorios = this.GetNumerosRandom();
            ViewBag.Random = aleatorios;
            return View(collatz);
        }
    }
}

PrimerCore/Controllers/PracticasController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerCore.Controllers
{
    public class PracticasController : Controller
    {
        //esto es un get
        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult EjemploColecciones()
        {
            List<Comic> listacomics = new List<Comic>();
            Comic comic = new Comic();
            comic.Nombre = "Naruto";
            comic.Descripcion = "Ninjas";
            comic.Imagen = "https://www.formulatv.com/images/series/posters/100/135/dest_1.jpg";
            listacomics.Add(comic);
            Comic comic2 = new Comic();
            comic2.Nombre = "Batman";
            comic2.Descripcion = "Hombre murcielago";
            comic2.Imagen = "https://www.normaeditorial.com/upload/media/albumes/0001/07/thumb_6662_albumes_big.jpeg";
            listacomics.Add(comic2);
            return View(listacomics);
        }

        public IActionResult SumarNumerosGet()
        {
            ViewBag.Num1 = 2;
            ViewBag.Num2 = 7;
            ViewBag.Suma = ViewBag.Num1 + ViewBag.Num2;
            return View();
        }
        public IActionResult SumarNumerosPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SumarNumerosPost(int num1, int num2)
        {
            ViewBag.Num1 = num1;
            ViewBag.Num2 = num2;
            ViewBag.Suma = num1 + num2;
            return View();
        }

        public IActionResult TablaMultiplicar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult TablaMultiplicar(int num)
        {
            List<FilaTabla> listafilas = new List<FilaTabla>();
            for (int i = 1;i <= 10; i++)
            {
                FilaTabla fila = new FilaTabla();
                fila.Columna1 = num + " * " + i;
                fila.Columna2 = num * i;
                listafilas.Add(fila);
            }

            return View(listafilas);
        }
    }
}

PrimerCore/Views/Practicas/EjemploColecciones.cshtml
@model List<Comic>

<h1>Colección de comics</h1>
<a asp-controller="Practicas"
   asp-action="Menu">
    Volver al menu
</a>
<hr/>

<table class="table table-dark">
    @foreach (Comic c in Model)
    {
        <tr>
            <td>@c.Nombre</td>
            <td>@c.Descripcion</td>
            <td><img src=@c.Imagen width="100" height="100"></td>
        </tr>
    }
</table>

PrimerCore/Views/Practicas/Menu.cshtml
<h1>Menú de practicas</h1>
<ul class="list-group">
    <li class="list-group-item">
        <a asp-controller="Practicas"
           asp-action="EjemploColecciones">
            Mostrar lista de comics
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Practicas"
           asp-action="SumarNumerosGet">
            Sumar numeros GET
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Practicas"
           asp-action="SumarnumerosPost">
            Sumar numeros POST
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Practicas"
           asp-action="TablaMultiplicar">
            Tabla de multiplicar
        </a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Matematicas"
           asp-action="ConjeturaCollatz">
            Conjetura Collatz
        </a>
    </li>
</ul>

PrimerCore/Views/Practicas/SumarNumerosGet.cshtml
<h1>Sumar numeros GET</h1>
<a asp-controller="Practicas"
   asp-action="Menu">
    Volver menu
</a>
<hr/>
<h2>@ViewBag.Num1 + @ViewBag.Num2 = @ViewBag.Suma</h2>

PrimerCore/Views/Practicas/SumarNumerosPost.cshtml
<h1>Sumar numeros POST</h1>
<a asp-controller="Practicas"
   asp-action="Menu">
    Volver menu
</a>
<hr />

<form method="post">
    <label>Numero 1: </label>
    <input type="number" name="num1"
           class="form-control" /><br />
    <label>Numero2: </label>
    <input type="number" name="num2"
           class="form-control" /><br />
    <button class="btn btn-info">
        Sumar números
    </button>
</form>
<hr />

@if (ViewBag.Suma != null)
{
    <h2 style="color:darkviolet">
        @ViewBag.Num1 + @ViewBag.Num2 = @ViewBag.Suma
    </h2>
}

PrimerCore/Views/Practicas/TablaMultiplicar.cshtml
@model List<FilaTabla>
<h1>Tabla de Multiplicar</h1>
<a asp-controller="Practicas"
   asp-action="Menu">
    Volver menu
</a>
<hr />

<form method="post">
    <label>Introduzca un número: </label>
    <input type="number" name="num"
           class="form-control" /><br />
    <button class="btn btn-info">
        Tabla de multiplicar
    </button>
</form>
<hr />

@if (ViewBag.Num != null)
{
    <table class="table table-dark">
        <tr>
            <td ><b>Multiplicación</b></td>
            <td><b>Resultado</b></td>
        </tr>
        @foreach(FilaTabla fila in Model)
        {
            <tr>
                <td>@fila.Columna1</td>           
                <td>@fila.Columna2</td>
            </tr>
        }
    </table>
}